<?php

define("ROOT", __DIR__.DIRECTORY_SEPARATOR);
define("MODEL", ROOT."Model".DIRECTORY_SEPARATOR);
define("VIEW", ROOT."View".DIRECTORY_SEPARATOR);
define("CONTROLLER", ROOT."Controller".DIRECTORY_SEPARATOR);
define("CORE", ROOT."Core".DIRECTORY_SEPARATOR);

?>